jobs:
  create-deployment:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - checkout
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          resource-file-path: tests/nginx-deployment/deployment.yaml
          resource-name: deployment/nginx-deployment
orbs:
  aws-eks: circleci/aws-eks@0.2.3
  kubernetes: circleci/kubernetes@0.4.0
version: 2.1
workflows:
  deployment:
    jobs:
      - aws-eks/create-cluster:
          context: AWS-CONTEXT
          cluster-name: eks-demo-deployment2
      - create-deployment:
          context: AWS-CONTEXT
          cluster-name: eks-demo-deployment2
          requires:
            - aws-eks/create-cluster
      - aws-eks/update-container-image:
          context: AWS-CONTEXT
          cluster-name: eks-demo-deployment2
          #container-image-updates: 'nginx=894218304272.dkr.ecr.ap-northeast-1.amazonaws.com/circleci-test/sample-orbs:latest'
          container-image-updates: 'nginx=nginx:1.9.1'
          #post-steps:
          #  - kubernetes/delete-resource:
          #      resource-names: nginx-deployment
          #      resource-types: deployment
          #      wait: true
          record: true
          requires:
            - create-deployment
          resource-name: deployment/nginx-deployment
      #- aws-eks/delete-cluster:
      #    context: AWS-CONTEXT
      #    cluster-name: eks-demo-deployment2
      #    requires:
      #      - aws-eks/update-container-image
